import { SCHEMA4_CAPABILITIES } from '../../../shared/schema4-capabilities.mjs'

export const RELEASE_INSPECTION_SURFACES = Object.freeze([
  'frontend',
  'pages',
  'worker',
  'schedule',
])

// This is the single independently authored surface-applicability authority.
// It is deliberately not generated by filtering the runtime gate registry.
export const RELEASE_INSPECTION_CAPABILITY_SURFACES = Object.freeze({
  leaderboardRead: Object.freeze(['frontend', 'pages']),
  identityClaim: Object.freeze(['frontend', 'pages', 'worker']),
  identityStatus: Object.freeze(['frontend', 'pages', 'worker']),
  identityRename: Object.freeze(['frontend', 'pages', 'worker']),
  draftSubmission: Object.freeze(['frontend', 'pages', 'worker']),
  identityRecovery: Object.freeze(['frontend', 'pages', 'worker']),
  cleanupCron: Object.freeze(['worker', 'schedule']),
})

const capabilityKeys = Object.keys(RELEASE_INSPECTION_CAPABILITY_SURFACES).sort()
const expectedKeys = [...SCHEMA4_CAPABILITIES].sort()
if (JSON.stringify(capabilityKeys) !== JSON.stringify(expectedKeys)) {
  throw new TypeError('Release-inspection capability applicability inventory is inconsistent.')
}
